SIU_Guarani/SIU_Guarani/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SIU_app.urls')),  # Vinculo todas las urls de mi app SIU
]

SIU_Guarani/SIU_app/urls.py
from django.urls import path
from .views import *

app_name = 'SIU' #Se especifica un nombre, para distinguir las urls similares de diferentes apps.
urlpatterns = [
    path('logout/', CerrarSesion.as_view(), name='cerrar_sesion'),
    path('acceso/', Logeo.as_view(), name='acceso'),
    path('acceso/recuperar', OlvidoContrasenna.as_view(), name='recuperar'),
    path('acceso/alta_usuario_cursos', CreoUsuario.as_view(), name='alta_usuario'),
    path('inicio_alumno/', InicioAlumno.as_view(), name='inicio_alumno'),
    path('materia/', InscripcionMaterias.as_view(), name='materia'),
    path('examen/', InscripcionExamenes.as_view(), name='examen'),
    path('plan_estudio/', ReportesPlanDeEstudio.as_view(), name='plan_estudio'),
    path('inscripciones/', ReportesMisInscripciones.as_view(), name='inscripciones'),
    path('porcentaje_avance_carrera/', PromedioYPorcentaje.as_view(), name='porcentaje_avance_carrera'),
    path('datos_censales/', MisDatosPersonales.as_view(), name='datos_censales'),
    path('datos_censales/domicilio/', Domicilio.as_view(), name='domicilio'),
    path('datos_censales/datos_contacto', DatosContacto.as_view(), name='datos_contacto'),
    path('datos_censales/editar_datos_contacto/datos_contacto/', ConfiguracionDatosCelular.as_view(),
         name='editar_datos_contacto'),
    path('datos_censales/discapacidad', Discapacidad.as_view(), name='discapacidad'),
    path('configuracion/', Configuracion.as_view(), name='configuracion'),
]

SIU_Guarani/SIU_app/admin/SIU/models/admin_alumno.py
from django.contrib import admin
from ....models import ALUMNO
from ... import mostrar_carrera_universitaria, mostrar_historial_academico


class AlumnoAdmin(admin.ModelAdmin):
    list_display = ('nombre', 'apellido', 'dni', 'nombre_carrera')
    list_filter = ('dni', 'id_carrera')
    search_fields = ('nombre', 'apellido', 'dni')
    actions = [mostrar_carrera_universitaria, mostrar_historial_academico]

    def nombre_carrera(self, obj):
        return obj.id_carrera
    nombre_carrera.short_description = "Carrera del alumno"


admin.site.register(ALUMNO, AlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_carrera.py
from django.contrib import admin
from ....models import CARRERA


class CarreraAdmin(admin.ModelAdmin):
    list_display = ('nombre_carrera',)


admin.site.register(CARRERA, CarreraAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_cursada_alumno.py
from django.contrib import admin
from ....models import CURSADA_ALUMNO
from ..actions import mostrar_materia_con_parcial


class CursadaAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'id_alumno', 'cursada_del_alumno')
    list_filter = ('id_alumno', 'inscripto', 'aprobo')
    search_fields = ('fecha',)
    actions = [mostrar_materia_con_parcial]

    def cursada_del_alumno(self, obj):
        return obj.id_materia_con_parcial
    cursada_del_alumno.short_description = 'Materias inscriptas del alumno'


admin.site.register(CURSADA_ALUMNO, CursadaAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen.py
from django.contrib import admin
from ....models import EXAMEN, EXAMEN_ALUMNO
from ..filters import RecentDateFilter


class ExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_examen', 'nota_examen', 'nombre_materia')
    list_filter = (RecentDateFilter,)

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_examen_alumno(tabla_examen_alumno):
        nota_examen = tabla_examen_alumno.id_materia_con_examen.id_examen.nota_examen

        if nota_examen >= 4:
            tabla_examen_alumno.aprobo = True
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()
        else:
            tabla_examen_alumno.aprobo = False
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_examen_alumno = EXAMEN_ALUMNO.objects.get(id_materia_con_examen__id_examen__id_examen=obj.id_examen)
        self.actualizo_examen_alumno(tabla_examen_alumno)


admin.site.register(EXAMEN, ExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen_alumno.py
from django.contrib import admin

from ..filters import RecentDateFilter
from ....models import EXAMEN_ALUMNO
from ..actions import mostrar_materia_con_examen


class ExamenAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'nombre_alumno', 'examen_del_alumno')
    list_filter = ('id_alumno', RecentDateFilter)
    actions = [mostrar_materia_con_examen]

    def examen_del_alumno(self, obj):
        return obj.id_materia_con_examen
    examen_del_alumno.short_description = 'Mesa de examen inscripta del alumno'

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'


admin.site.register(EXAMEN_ALUMNO, ExamenAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_historial_academico.py
from django.contrib import admin

from ....models import HISTORIAL_ACADEMICO
from ..filters import RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter
from ..actions import mostrar_cursada_alumno, mostrar_examen_alumno


class HistorialAcademicoAdmin(admin.ModelAdmin):
    list_display = ('nombre_alumno', 'fecha', 'nombre_cursada_alumno', 'nombre_examen_alumno')
    list_filter = (RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter)
    search_fields = ('id_alumno__dni',)
    actions = [mostrar_cursada_alumno, mostrar_examen_alumno]

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'

    def nombre_cursada_alumno(self, obj):
        return obj.id_cursada_alumno
    nombre_cursada_alumno.short_description = 'Cursada regular del alumno'

    def nombre_examen_alumno(self, obj):
        return obj.id_examen_alumno
    nombre_examen_alumno.short_description = 'Mesa de examen del alumno'


admin.site.register(HISTORIAL_ACADEMICO, HistorialAcademicoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_examen.py
from django.contrib import admin
from ....models import MATERIA_CON_EXAMEN
from ..actions import cargo_notas_examen


class MateriaConExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_examen')
    actions = [cargo_notas_examen]

    def nombre_examen(self, obj):
        return obj.id_examen
    nombre_examen.short_description = 'Examen'

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'


admin.site.register(MATERIA_CON_EXAMEN, MateriaConExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_parcial.py
from django.contrib import admin
from ....models import MATERIA_CON_PARCIAL
from ..actions import mostrar_parciales


class MateriaConParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_primer_parcial', 'nombre_segundo_parcial')
    list_filter = ('id_materia', 'id_materia_con_parcial')
    actions = [mostrar_parciales]

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    def nombre_primer_parcial(self, obj):
        return obj.id_primer_parcial
    nombre_primer_parcial.short_description = "Pimer parcial"

    def nombre_segundo_parcial(self, obj):
        return obj.id_segundo_parcial
    nombre_segundo_parcial.short_description = "Segundo parcial"


admin.site.register(MATERIA_CON_PARCIAL, MateriaConParcialAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_parcial.py
from django.contrib import admin
from django.db.models import Q
from ....models import PARCIAL, CURSADA_ALUMNO


class ParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_parcial', 'nota_parcial', 'nota_recuperatorio', 'nota_promocion', 'nombre_materia')
    list_filter = ('nombre_parcial',)

    def nombre_materia(self, obj):
        return obj.id_materia

    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_cursada_alumno(tabla_cursada_alumno):
        nota_primer_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_promocion
        nota_primer_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_parcial
        nota_primer_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_recuperatorio
        nota_segundo_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_promocion
        nota_segundo_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_parcial
        nota_segundo_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_recuperatorio

        if nota_primer_parcial < 4:
            if nota_primer_recuperatorio != 0 and nota_primer_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial != 0 and nota_segundo_parcial < 4)):
            if nota_segundo_recuperatorio != 0 and nota_segundo_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

            elif nota_segundo_recuperatorio >= 4:
                tabla_cursada_alumno.aprobo = True
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if (nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4 and
                nota_segundo_parcial == 0):
            pass
        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial >= 4 or nota_segundo_recuperatorio >= 4 or nota_segundo_promocion >= 4)):
            tabla_cursada_alumno.aprobo = True
            tabla_cursada_alumno.inscripto = False
            tabla_cursada_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_cursada_alumno = CURSADA_ALUMNO.objects.get(
            Q(id_materia_con_parcial__id_primer_parcial__id_parcial=obj.id_parcial) |
            Q(id_materia_con_parcial__id_segundo_parcial__id_parcial=obj.id_parcial)
        )
        self.actualizo_cursada_alumno(tabla_cursada_alumno)


admin.site.register(PARCIAL, ParcialAdmin)

SIU_Guarani/SIU_app/views.py
from django.shortcuts import render

# Create your views here.

SIU_Guarani/SIU_app/templates/SIU/templates_base/datos_personales_base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SIU Guaraní{% endblock %}</title>
    <link rel="icon" href="{% static 'SIU/imagenes/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/navegadores/columna_navegador_datos_personales.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/navegadores/navegador_alumno.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/navegadores/navegador_paginas.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/inputs/inputs.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/inputs/inputs_numericos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/inputs/boton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/textos/texto_azul.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/textos/texto_gris.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/cuerpo.css' %}">
    <script src="{% static 'SIU/java_script/Opciones_alumno_navegador.js' %}"></script>

</head>
<style>
    .contenedor{
        width: 1170px;
        height: 870px;
        display: flex;
        margin-left: auto; /* Margen izquierdo automático */
        margin-right: auto; /* Margen derecho automático */
    }
    .sub_contenedor{
        width: 1170px;
        height: 800px;
        margin-left: auto; /* Margen izquierdo automático */
        margin-right: auto; /* Margen derecho automático */
        align-items: center;
        justify-content: center;
    }
    .titulo_operacion{
        width: 1170px;
        height: 44px;
        display: flex;
        justify-items: center;
        align-items: center;
    }
    .sub_titulo_operacion{
        width: 1170px;
        height: 36px;
        display: flex;
        justify-items: center;
        align-items: center;
        margin-bottom: -8px;
        border-bottom: 1px solid rgb(238, 238, 238);
    }
    .titulo{
        width: 570px;
        height: 35px;
        display: flex;
        align-items: center;
        justify-items: center;
        line-height: 20px;
        box-sizing: border-box;
    }

    .dos_columnas{
        width: 1170px;
        height: 644px;
        display: flex;
    }

    .nota_alerta{
        width: 870px;
        height: 58px;
        background: #D9EDF7;
        display: flex;
        border-radius: 5px;
        margin-top: 10px;
    }
    .sub_nota_alerta{
        width: 820px;
        height: 40px;
        text-align: center;
        align-self: center;
    }

    .columna_datos_personales{
        width: 870px;
        height: 800px;
        margin-left: 20px;
    }
    .sub_columna_datos_personales{
        width: 870px;
        height: 800px;
        margin-left: 20px;
    }

    .titulo_edicion_datos_personales{
        width: 870px;
        height: 41px;
        display: flex;
        align-items: center;
        align-content: center;
        justify-content: space-between;
        border-bottom: 1px solid rgb(238, 238, 238);
    }

    /* Estilo para la ventana emergente */
    .custom-alert {
        position: fixed;
        top: -100px; /* Inicialmente fuera de la pantalla */
        left: 50%;
        transform: translateX(-50%);
        padding: 4px;
        background-color: #D9EDF7;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        z-index: 9999;
        transition: top 0.5s ease; /* Animación de entrada */
        font-size: 14px;
        color: #42ADE8;
    }
    /* Estilo para el botón de cerrar */
    .custom-alert .closebtn {
        position: absolute;
        top: 5px;
        right: 10px;
        cursor: pointer;
    }

    {% block style %}


    {% endblock %}

    a{
        text-decoration: none;
        color: black;
    }

    li{
        list-style: none; /* Elimina las viñetas */
    }
</style>
<body>
    <div class="contenedor_alumno_principal">
        <div class="sub_contenedor_alumno_principal">
            <div class="logo_untdf">
                <a href="{% url 'SIU:inicio_alumno' %}"><img src="{% static 'SIU/imagenes/logo-transparente.png' %}"></a>
            </div>
            <div class="datos_alumno">
                <div class="opciones_alumno">
                    <button onclick="mostrarOpciones_alumno()" class="boton-sin-contorno">{{ usuario.nombre }} {{ usuario.apellido }}</button>
                    <ul id="lista_opciones_alumno" class="lista_opciones_reportes" style="display: none">
                            <li class="li_lista_opciones_alumno"><a href="{% url 'SIU:configuracion' %}"> Configuración</a></li>
                            <li class="li_lista_opciones_alumno"><a href="{% url 'SIU:cerrar_sesion' %}">Cerrar sesión</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="navegador">
        <div class="sub_navegador">
            <button class="nueva_pagina"><a href="{% url 'SIU:materia' %}" class="salto_pagina_texto">Inscripción a Materias</a></button>
            <button class="nueva_pagina"><a href="{% url 'SIU:examen' %}" class="salto_pagina_texto">Inscripción a Exámenes</a></button>
            <div style="position: relative">
                <button class="nueva_pagina salto_pagina_texto" onclick="mostrarOpciones_navegador()" >Reportes</button>
                <ul id="lista_opciones_navegador" class="lista_opciones_reportes" style="display: none">
                    <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:plan_estudio' %}">Plan de estudio</a></li>
                    <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:inscripciones' %}">Mis inscripciones</a></li>
                    <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:porcentaje_avance_carrera' %}">Promedio y porcentaje de avance en la carrera</a></li>
                </ul>
            </div>
            <button class="pagina_actual"><a href="{% url 'SIU:datos_censales' %}" class="pagina_actual_texto">Mis datos personales</a> </button>
        </div>
    </div>

    <!-- La alerta si se guardan los cambios -->
    <div id="customAlert" class="custom-alert">
        <span class="closebtn" onclick="cerrarAlerta()">&times;</span>
        <p id="alerta_texto"></p>
    </div>

    <!--Contenedor principal de la pagina-->
    <div class="contenedor">
        <div class="sub_contenedor">
            <div class="titulo_operacion">
                <div class="sub_titulo_operacion">
                    <div class="titulo">
                        <h2 class="texto_azul" style="border-bottom: none">Mis datos personales</h2>
                    </div>
                </div>
            </div><br>
            <div class="dos_columnas">

                <!-- Navegador de los diferentes datos personales-->
                <div class="columna_links_datos">
                    <div class="sub_columna_links">
                        <div class="links">
                            <ul>
                                {% block navegador_datos_personales %}


                                {% endblock %}
                            </ul>
                        </div>
                        <div class="nota">
                            <p style="margin-left: 10px;"><strong>Última confirmación: 05/05/2024</strong></p>
                            <hr style="margin-top: -10px">
                            <p style="margin-left: 10px">Los campos marcados con<strong>(*)</strong> son obligatorios.
                                <br>
                                <br>
                            Una vez que hatas acutlizado tus datos, presioná el botón<strong>"Confirmar".</strong></p>
                        </div>
                    </div>
                </div>

                <!-- Tabla de datos personales del usuario -->
                <div class="columna_datos_personales">
                    <div class="sub_columna_datos_personales">
                        <div class="nota_alerta">
                            <div class="sub_nota_alerta">Tus datos se encuentran vigentes. De todas maneras, si tenés
                            algún dato para modificar, no olvides presionar el botón "Confirmar"
                            al finalizar para indicar que se encuentran actualizados.</div>
                        </div>

                        <!--Formulario y datos del usuario-->
                        <form method="post">{% csrf_token %}
                            <div class="titulo_edicion_datos_personales">
                                <h2 class="texto_gris" style="font-size: 24px; border: none">{% block titulo_pagina %}Datos personales{% endblock %}</h2>
                            </div><br>

                            <!-- Contenido específico de cada página -->
                            {% block content %}

                            {% endblock %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        const cambioCorrecto = {{ cambio|lower }};

        // Función para mostrar la alerta
        if (cambioCorrecto) {
             document.getElementById('alerta_texto').innerHTML = "Se guardó correctamente";
            let alerta = document.getElementById("customAlert");
            alerta.style.top = "0"; // Mover la alerta hacia abajo
            alerta.style.background = '#DFF0D8';
            alerta.style.color = '#55DE68';
            alerta.style.borderColor = '#DAEBD3';
            setTimeout(function() {
                alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
            }, 5000); // 5000 milisegundos = 5 segundos
        }

        // Función para cerrar la alerta
        function cerrarAlerta() {
            let alerta = document.getElementById("customAlert");
            alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
        }
    </script><!-- El script de alerta si se cambiaron los datos -->
    <script>
        const sincambioCorrecto = {{ no_hay_cambio|lower }};
        if(sincambioCorrecto){
            document.getElementById('alerta_texto').innerHTML = "No hay cambios para guardar";
            let alerta = document.getElementById("customAlert");
            alerta.style.top = "0"; // Mover la alerta hacia abajo
            setTimeout(function() {
                alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
            }, 5000); // 5000 milisegundos = 5 segundos
        }
                // Función para cerrar la alerta
        function cerrarAlerta() {
            let alerta = document.getElementById("customAlert");
            alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
        }
</script><!--El script de alerta si no hubo cambios de datos-->

    <!-- Scripts adicionales -->
    {% block script %}

    {% endblock %}
</body>
</html>

SIU_Guarani/SIU_app/templates/SIU/templates_base/navegador_base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SIU Guaraní{% endblock %}</title>
    <link rel="icon" href="{% static 'SIU/imagenes/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/navegadores/navegador_paginas.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/navegadores/navegador_alumno.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/inputs/inputs.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/inputs/boton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/textos/texto_azul.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/textos/texto_gris.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/notas/alerta_inscripciones.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/cuerpo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'SIU/css/alerta_inscripcion.css' %}">
    <script src="{% static 'SIU/java_script/Opciones_alumno_navegador.js' %}"></script>
    <script src="{% static 'SIU/java_script/BotonDarDeBajaMateria.js' %}"></script>
</head>
<style>
    /* Estilo para la ventana emergente */
    .custom-alert-notificacion {
        position: fixed;
        top: -100px; /* Inicialmente fuera de la pantalla */
        left: 50%;
        transform: translateX(-50%);
        padding: 4px;
        background-color: #D9EDF7;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        z-index: 9999;
        transition: top 0.5s ease; /* Animación de entrada */
        font-size: 14px;
        color: #42ADE8;
    }
    /* Estilo para el botón de cerrar */
    .custom-alert-notificacion .closebtn {
        position: absolute;
        top: 5px;
        right: 10px;
        cursor: pointer;
    }

    {% block style %}


    {% endblock %}
    a{
        text-decoration: none;
        color: black;
    }

    li{
        list-style: none; /* Elimina las viñetas */
    }

    .lista_opciones_reportes{
        background-clip: padding-box;
        border: 1px solid rgba(0, 0, 0, 0.2);
        border-radius: 6px;
        box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 10px 0px;
        display: block;
        float: none;
        line-height: 20px;
        margin-block-start: 2px;
        margin-top: 2px;
        padding-top: 5px;
        padding-bottom: 5px;
        position: absolute;
        text-align: left;
        top: 40px;
        z-index: 1000;
    }
    .li_lista_opciones_reportes{
        color: rgb(51, 51, 51);
        display: list-item;
        line-height: 20px;
        line-style-position: outside;
        text-align: left;
        text-size-adjust: 100%;
    }
</style>
<body>
<!--La barra superior de navegador y configuracion -->
    <div class="contenedor_alumno_principal">
        <div class="sub_contenedor_alumno_principal">
            <div class="logo_untdf">
                <a href="{% url 'SIU:inicio_alumno' %}"><img src="{% static 'SIU/imagenes/logo-transparente.png' %}"></a>
            </div>
            <div class="datos_alumno">
                <div class="opciones_alumno">
                    <button onclick="mostrarOpciones_alumno()" class="boton-sin-contorno">{{ usuario.nombre }} {{ usuario.apellido }}</button>
                    <ul id="lista_opciones_alumno" class="lista_opciones_reportes" style="display: none">
                        <li class="li_lista_opciones_alumno"><a href="{% url 'SIU:configuracion' %}"> Configuración</a></li>
                        <li class="li_lista_opciones_alumno"><a href="{% url 'SIU:cerrar_sesion' %}">Cerrar sesión</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navegador">
        <div class="sub_navegador">
            {% block navegador %}


            {% endblock %}
        </div>
    </div>

<!-- La alerta si falla algo -->
    <div id="customAlert" class="custom-alert">
        <span class="closebtn" onclick="cerrarAlerta()">&times;</span>
        <p id="alerta_texto"></p>
    </div>

<!--Contenido de cada pagina-->
    {% block content %}

    {% endblock %}

<!-- Scripts adicionales -->
    {% block script %}

    {% endblock %}
</body>
</html>