SIU_Guarani/SIU_Guarani/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SIU_app.urls')),  # Vinculo todas las urls de mi app SIU
]

SIU_Guarani/SIU_app/urls.py
from django.urls import path
from .views import *

app_name = 'SIU' #Se especifica un nombre, para distinguir las urls similares de diferentes apps.
urlpatterns = [
    path('logout/', CerrarSesion.as_view(), name='cerrar_sesion'),
    path('acceso/', Logeo.as_view(), name='acceso'),
    path('acceso/recuperar', OlvidoContrasenna.as_view(), name='recuperar'),
    path('acceso/alta_usuario_cursos', CreoUsuario.as_view(), name='alta_usuario'),
    path('inicio_alumno/', InicioAlumno.as_view(), name='inicio_alumno'),
    path('materia/', InscripcionMaterias.as_view(), name='materia'),
    path('examen/', InscripcionExamenes.as_view(), name='examen'),
    path('plan_estudio/', ReportesPlanDeEstudio.as_view(), name='plan_estudio'),
    path('inscripciones/', ReportesMisInscripciones.as_view(), name='inscripciones'),
    path('porcentaje_avance_carrera/', PromedioYPorcentaje.as_view(), name='porcentaje_avance_carrera'),
    path('datos_censales/', MisDatosPersonales.as_view(), name='datos_censales'),
    path('datos_censales/domicilio/', Domicilio.as_view(), name='domicilio'),
    path('datos_censales/datos_contacto', DatosContacto.as_view(), name='datos_contacto'),
    path('datos_censales/editar_datos_contacto/datos_contacto/', ConfiguracionDatosCelular.as_view(),
         name='editar_datos_contacto'),
    path('datos_censales/discapacidad', Discapacidad.as_view(), name='discapacidad'),
    path('configuracion/', Configuracion.as_view(), name='configuracion'),
]

SIU_Guarani/SIU_app/admin/SIU/models/admin_alumno.py
from django.contrib import admin
from ....models import ALUMNO
from ... import mostrar_carrera_universitaria, mostrar_historial_academico


class AlumnoAdmin(admin.ModelAdmin):
    list_display = ('nombre', 'apellido', 'dni', 'nombre_carrera')
    list_filter = ('dni', 'id_carrera')
    search_fields = ('nombre', 'apellido', 'dni')
    actions = [mostrar_carrera_universitaria, mostrar_historial_academico]

    def nombre_carrera(self, obj):
        return obj.id_carrera
    nombre_carrera.short_description = "Carrera del alumno"


admin.site.register(ALUMNO, AlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_carrera.py
from django.contrib import admin
from ....models import CARRERA


class CarreraAdmin(admin.ModelAdmin):
    list_display = ('nombre_carrera',)


admin.site.register(CARRERA, CarreraAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_cursada_alumno.py
from django.contrib import admin
from ....models import CURSADA_ALUMNO
from ..actions import mostrar_materia_con_parcial


class CursadaAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'id_alumno', 'cursada_del_alumno')
    list_filter = ('id_alumno', 'inscripto', 'aprobo')
    search_fields = ('fecha',)
    actions = [mostrar_materia_con_parcial]

    def cursada_del_alumno(self, obj):
        return obj.id_materia_con_parcial
    cursada_del_alumno.short_description = 'Materias inscriptas del alumno'


admin.site.register(CURSADA_ALUMNO, CursadaAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen.py
from django.contrib import admin
from ....models import EXAMEN, EXAMEN_ALUMNO
from ..filters import RecentDateFilter


class ExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_examen', 'nota_examen', 'nombre_materia')
    list_filter = (RecentDateFilter,)

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_examen_alumno(tabla_examen_alumno):
        nota_examen = tabla_examen_alumno.id_materia_con_examen.id_examen.nota_examen

        if nota_examen >= 4:
            tabla_examen_alumno.aprobo = True
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()
        else:
            tabla_examen_alumno.aprobo = False
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_examen_alumno = EXAMEN_ALUMNO.objects.get(id_materia_con_examen__id_examen__id_examen=obj.id_examen)
        self.actualizo_examen_alumno(tabla_examen_alumno)


admin.site.register(EXAMEN, ExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen_alumno.py
from django.contrib import admin

from ..filters import RecentDateFilter
from ....models import EXAMEN_ALUMNO
from ..actions import mostrar_materia_con_examen


class ExamenAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'nombre_alumno', 'examen_del_alumno')
    list_filter = ('id_alumno', RecentDateFilter)
    actions = [mostrar_materia_con_examen]

    def examen_del_alumno(self, obj):
        return obj.id_materia_con_examen
    examen_del_alumno.short_description = 'Mesa de examen inscripta del alumno'

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'


admin.site.register(EXAMEN_ALUMNO, ExamenAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_historial_academico.py
from django.contrib import admin

from ....models import HISTORIAL_ACADEMICO
from ..filters import RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter
from ..actions import mostrar_cursada_alumno, mostrar_examen_alumno


class HistorialAcademicoAdmin(admin.ModelAdmin):
    list_display = ('nombre_alumno', 'fecha', 'nombre_cursada_alumno', 'nombre_examen_alumno')
    list_filter = (RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter)
    search_fields = ('id_alumno__dni',)
    actions = [mostrar_cursada_alumno, mostrar_examen_alumno]

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'

    def nombre_cursada_alumno(self, obj):
        return obj.id_cursada_alumno
    nombre_cursada_alumno.short_description = 'Cursada regular del alumno'

    def nombre_examen_alumno(self, obj):
        return obj.id_examen_alumno
    nombre_examen_alumno.short_description = 'Mesa de examen del alumno'


admin.site.register(HISTORIAL_ACADEMICO, HistorialAcademicoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_examen.py
from django.contrib import admin
from ....models import MATERIA_CON_EXAMEN
from ..actions import cargo_notas_examen


class MateriaConExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_examen')
    actions = [cargo_notas_examen]

    def nombre_examen(self, obj):
        return obj.id_examen
    nombre_examen.short_description = 'Examen'

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'


admin.site.register(MATERIA_CON_EXAMEN, MateriaConExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_parcial.py
from django.contrib import admin
from ....models import MATERIA_CON_PARCIAL
from ..actions import mostrar_parciales


class MateriaConParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_primer_parcial', 'nombre_segundo_parcial')
    list_filter = ('id_materia', 'id_materia_con_parcial')
    actions = [mostrar_parciales]

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    def nombre_primer_parcial(self, obj):
        return obj.id_primer_parcial
    nombre_primer_parcial.short_description = "Pimer parcial"

    def nombre_segundo_parcial(self, obj):
        return obj.id_segundo_parcial
    nombre_segundo_parcial.short_description = "Segundo parcial"


admin.site.register(MATERIA_CON_PARCIAL, MateriaConParcialAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_parcial.py
from django.contrib import admin
from django.db.models import Q
from ....models import PARCIAL, CURSADA_ALUMNO


class ParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_parcial', 'nota_parcial', 'nota_recuperatorio', 'nota_promocion', 'nombre_materia')
    list_filter = ('nombre_parcial',)

    def nombre_materia(self, obj):
        return obj.id_materia

    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_cursada_alumno(tabla_cursada_alumno):
        nota_primer_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_promocion
        nota_primer_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_parcial
        nota_primer_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_recuperatorio
        nota_segundo_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_promocion
        nota_segundo_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_parcial
        nota_segundo_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_recuperatorio

        if nota_primer_parcial < 4:
            if nota_primer_recuperatorio != 0 and nota_primer_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial != 0 and nota_segundo_parcial < 4)):
            if nota_segundo_recuperatorio != 0 and nota_segundo_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

            elif nota_segundo_recuperatorio >= 4:
                tabla_cursada_alumno.aprobo = True
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if (nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4 and
                nota_segundo_parcial == 0):
            pass
        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial >= 4 or nota_segundo_recuperatorio >= 4 or nota_segundo_promocion >= 4)):
            tabla_cursada_alumno.aprobo = True
            tabla_cursada_alumno.inscripto = False
            tabla_cursada_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_cursada_alumno = CURSADA_ALUMNO.objects.get(
            Q(id_materia_con_parcial__id_primer_parcial__id_parcial=obj.id_parcial) |
            Q(id_materia_con_parcial__id_segundo_parcial__id_parcial=obj.id_parcial)
        )
        self.actualizo_cursada_alumno(tabla_cursada_alumno)


admin.site.register(PARCIAL, ParcialAdmin)

SIU_Guarani/SIU_app/views.py
from django.shortcuts import render

# Create your views here.

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/configuracion/configuracion.html
{% extends 'SIU/templates_base/navegador_base.html' %}

{% block title %}SIU Guaraní - Configuración{% endblock %}

{% block style %}
    .contenedor_principal{
        width: 1170px;
        height: 549px;
        margin-left: auto; /* Margen izquierdo automático */
        margin-right: auto; /* Margen derecho automático */
    }
    .titulo_operaciones{
        width: 1170px;
        height: 55px;
    }
    .sub_titulo_operaciones{
        width: 1170px;
        height: 55px;
    }
    .contenedor_configuracion{
        width: 1170px;
        height: 494px;
    }
    .sub_contenedor_configuracion{
        width: 1170px;
        height: 494px;
    }
    .dos_contenedores{
        width: 1170px;
        height: 218px;
        display: flex;
    }
    .notificacion{
        width: 570px;
        height: 133px;
    }
    .formulario_notificaciones{
        width: 570px;
        height: 103px;
    }
    .formulario_mail{
        width: 570px;
        height: 60px;
    }
    .control_input{
        width: 570px;
        height: 30px;
    }
    .cambiar_contrasenna{
        width: 570px;
        height: 218px;
        align-items: flex-end
    }
    .formulario_contrasenna{
        width: 570px;
        height: 145px;
        display: flex;
        justify-content: center;
    }
    .sub_formulario{
        width: 530px;
        height: 140px;
        align-content: center;
    }
    .contrasenna_configuracion{
        width: 570px;
        height: 45px;
        display: flex;
        justify-content: space-between;
    }
    .controlador{
        width: 390px;
        height: 45px;
    }

    .sub_contenedor_titulo{
        height: 51px;
        display: flex;
        justify-content: space-between;
        align-items: center
    }

    .red_input {
        background-color: #ffcccc; /* Cambiar aquí el color de fondo a rojo claro */
        border-color: #dddddd; /* Cambiar el color del borde a rojo */
    }
    /* Estilo para la ventana emergente */
    .custom-alert {
        position: fixed;
        top: -100px; /* Inicialmente fuera de la pantalla */
        left: 50%;
        transform: translateX(-50%);
        padding: 4px;
        background-color: #ffcccc;
        border: 1px solid #ccc;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        z-index: 9999;
        transition: top 0.5s ease; /* Animación de entrada */
        font-family: Arial;
        font-size: 14px;
        color: red;
        border-redius: 5px;
    }
    /* Estilo para el botón de cerrar */
    .custom-alert .closebtn {
        position: absolute;
        top: 5px;
        right: 10px;
        cursor: pointer;
    }
{% endblock %}

{% block navegador %}
    <button class="nueva_pagina"><a href="{% url 'SIU:materia' %}" class="salto_pagina_texto">Inscripción a Materias</a></button>
    <button class="nueva_pagina"><a href="{% url 'SIU:examen' %}" class="salto_pagina_texto">Inscripción a Exámenes</a></button>
    <div style="position: relative">
        <button class="nueva_pagina salto_pagina_texto" onclick="mostrarOpciones_navegador()" >Reportes</button>
        <ul id="lista_opciones_navegador" class="lista_opciones_reportes" style="display: none">
            <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:plan_estudio' %}">Plan de estudio</a></li>
            <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:inscripciones' %}">Mis inscripciones</a></li>
            <li class="li_lista_opciones_reportes"><a href="{% url 'SIU:porcentaje_avance_carrera' %}">Promedio y porcentaje de avance en la carrera</a></li>
        </ul>
    </div>
    <button class="nueva_pagina"><a href="{% url 'SIU:datos_censales' %}" class="salto_pagina_texto">Mis datos personales</a> </button>
{% endblock %}

{% block titulo_pagina %}Datos de contacto{% endblock %}

{% block navegador_datos_personales %}
        <li><a href="{% url 'SIU:datos_censales' %}" class="li_links">Datos personales</a></li>
        <li><a href="{% url 'SIU:domicilio' %}" class="li_links">Domicilio</a></li>
        <li id="pagina_actual_links"><a href="{% url 'SIU:datos_contacto' %}" class="pagina_actual_texto">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li><a href="{% url 'SIU:discapacidad' %}" class="li_links">Discapacidad</a></li>
{% endblock %}

{% block content %}

<!-- La estructura de los inputs y configuraciones-->
    <div class="contenedor_principal">
            <div class="titulo_operaciones">
                <div class="sub_titulo_operaciones">
                    <h2 class="texto_azul">Configuración</h2>
                </div>
            </div>
            <div class="contenedor_configuracion">
                <div class="sub_contenedor_configuracion">
                    <form method="post">{% csrf_token %}
                        <div class="dos_contenedores">

                            <div class="notificacion">
                                <div class="formulario_notificaciones">
                                    <div class="sub_contenedor_titulo">
                                        <h3 class="texto_gris"><span class="pull_left">Notificaciones</span> </h3>
                                        <button id="boton_cambiar_mail" class="boton" style="display: none" type="submit">Aceptar</button>
                                    </div>
                                    <div class="formulario_mail">
                                        <div class="control_input">
                                            <label for="{{ form.name }}">{{ form.mail.label}}</label>
                                            {{ form.mail }}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cambiar_contrasenna">
                                <div class="sub_contenedor_titulo">
                                    <h3 class="texto_gris">Cambiar contraseña</h3>
                                    <button id="boton_cambiar_contrasenna" class="boton" style="display: none" type="submit">Aceptar</button>
                                </div>
                                {% if no_coincide_contrasenna_actual %}
                                    <div class="formulario_contrasenna">
                                        <div class="sub_formulario">
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.contrasenna_actual.label}}</label>
                                                <div class="controlador">
                                                    {{ form.contrasenna_actual }}
                                                </div>
                                            </div>
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.contrasenna_nueva.label}}</label>
                                                <div class="controlador">
                                                    {{ form.contrasenna_nueva }}
                                                </div>
                                            </div>
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.confirmar_contrasenna_nueva.label}}</label>
                                                <div class="controlador">
                                                    {{ form.confirmar_contrasenna_nueva }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="formulario_contrasenna">
                                        <div class="sub_formulario">
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.contrasenna_actual.label}}</label>
                                                <div class="controlador">
                                                    {{ form.contrasenna_actual }}
                                                </div>
                                            </div>
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.contrasenna_nueva.label}}</label>
                                                <div class="controlador">
                                                    {{ form.contrasenna_nueva }}
                                                </div>
                                            </div>
                                            <div class="contrasenna_configuracion">
                                                <label for="{{ form.name }}">{{ form.confirmar_contrasenna_nueva.label}}</label>
                                                <div class="controlador">
                                                    {{ form.confirmar_contrasenna_nueva }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    <script>
        // Selecciona y guardo los inputs necesarios

        const inputs = [
            document.getElementById('contrasenna_actual'),
            document.getElementById('contrasenna_nueva'),
            document.getElementById('confirmar_contrasenna')
        ];
        const inputMail = document.getElementById('mail');

        // Creo las funciones necesarias que se agregan en los eventos

        const checkInputs = () => {
            const boton = document.getElementById('boton_cambiar_contrasenna');
            const allFilled = inputs.every(input => input.value.trim() !== '');
            if (allFilled){
                boton.style.display = 'block';
            }
            else {
                boton.style.display = 'none';
            }
        };
        const checkMailInput = () => {
            const value = inputMail.value.trim();
            const botonAceptarMail = document.getElementById('boton_cambiar_mail');
            if (value !== '') {
                botonAceptarMail.style.display = 'block'
            } else {
                botonAceptarMail.style.display = 'none'
            }
        };

        //Creo los eventos para los inputs

        inputs.forEach(input => {
            input.addEventListener('input', checkInputs);
        });
        inputMail.addEventListener('input', checkMailInput);
    </script><!-- Controlador de aparicion de botones -->
    <script>
    // Función para mostrar la alerta
    function mostrarAlerta() {
        let alerta = document.getElementById("customAlert");
        alerta.style.top = "0"; // Mover la alerta hacia abajo
        setTimeout(function() {
            alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
        }, 5000); // 5000 milisegundos = 5 segundos
    }

    // Función para cerrar la alerta
    function cerrarAlerta() {
        let alerta = document.getElementById("customAlert");
        alerta.style.top = "-100px"; // Mover la alerta fuera de la pantalla
    }
    </script><!-- El script de las alertas si ingreso mal la contraseña -->
    <script>
        //Creo la modificacion del css si ingresan mal la contraseña actual
        const inputMalIngresado = document.querySelector('#contrasenna_actual');
        const noCoincideContrasennaActual = {{ no_coincide_contrasenna_actual|lower }};

        if (noCoincideContrasennaActual) {
            inputMalIngresado.classList.add('red_input');
            document.getElementById('alerta_texto').innerHTML = "La contraseña ingresada no coincide";
            mostrarAlerta();
        }
    </script><!-- Contraseña actual falla -->
    <script>
        //Creo la modificacion del css si ingresan mal la contraseña nueva
        const inputMalIngresado = document.querySelector('#confirmar_contrasenna');
        const noCoincideContrasennaNueva = {{ cambio|lower }};

        if (!noCoincideContrasennaNueva) {
            inputMalIngresado.classList.add('red_input');
            document.getElementById('alerta_texto').innerHTML = "La contraseña nueva no coincide";
            mostrarAlerta();
        }
        else {
            document.getElementById('alerta_texto').innerHTML = "La contraseña se actualizo";
            mostrarAlerta();
        }
    </script><!-- Contraseña nueva opciones -->
{% endblock %}

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/configuracion/configuracion_datos_celular.html
{% extends 'SIU/templates_base/datos_personales_base.html' %}

{% block title %}SIU Guaraní - Datos censales{% endblock %}

{% block style %}
    .cambio_datos_celular{
        width: 870px;
        height: 180px;
        background: #F5F5F5;
        border: 1px solid rgb(227, 227, 227);
        border-radius: 5px;
        box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 1px 0px inset;
        margin-bottom: 20px;
        padding-right: 10px;
        padding-left: 10px;
    }

    .telefono{
        margin-bottom: 5px;
        width: 870px;
        height: 65px;
        display: flex;
    }

    .cod_telefono{
        width: 123.2px;
        height: 65px;
        box-sizing: border-box;
    }

    .numero_telefono{
        width: 413.11px;
        height: 65px;
        box-sizing: border-box;
        margin-left: 22px;
    }
{% endblock %}

{% block titulo_pagina %}Datos de contacto{% endblock %}

{% block navegador_datos_personales %}
        <li><a href="{% url 'SIU:datos_censales' %}" class="li_links">Datos personales</a></li>
        <li><a href="{% url 'SIU:domicilio' %}" class="li_links">Domicilio</a></li>
        <li id="pagina_actual_links"><a href="{% url 'SIU:datos_contacto' %}" class="pagina_actual_texto">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li><a href="{% url 'SIU:discapacidad' %}" class="li_links">Discapacidad</a></li>
{% endblock %}

{% block content %}
        <div class="cambio_datos_celular">
            <h3 class="texto_gris">Contacto</h3>
            <label for="{{ form.name }}"><strong>{{form.tipo_de_contacto.label}}</strong></label><br>
            {{form.tipo_de_contacto}}
            <div class="telefono">
                <div class="cod_telefono">
                    <label for="{{ form.name }}">{{ form.cod_area.label }}</label>
                    {{ form.cod_area }}
                </div>
                <div class="numero_telefono" >
                    <label for="{{ form.name }}">{{ form.numero.label }}</label><br>
                    {{form.numero}}
                </div>
            </div>
        </div><br>
        <div>
            <button class="boton" name="boton_guardar" value="True" type="submit">Guardar</button>
            <button class="boton" name="boton_volver" value="True" type="submit">Volver</button>
        </div>
{% endblock %}