SIU_Guarani/SIU_Guarani/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SIU_app.urls')),  # Vinculo todas las urls de mi app SIU
]

SIU_Guarani/SIU_app/urls.py
from django.urls import path
from .views import *

app_name = 'SIU' #Se especifica un nombre, para distinguir las urls similares de diferentes apps.
urlpatterns = [
    path('logout/', CerrarSesion.as_view(), name='cerrar_sesion'),
    path('acceso/', Logeo.as_view(), name='acceso'),
    path('acceso/recuperar', OlvidoContrasenna.as_view(), name='recuperar'),
    path('acceso/alta_usuario_cursos', CreoUsuario.as_view(), name='alta_usuario'),
    path('inicio_alumno/', InicioAlumno.as_view(), name='inicio_alumno'),
    path('materia/', InscripcionMaterias.as_view(), name='materia'),
    path('examen/', InscripcionExamenes.as_view(), name='examen'),
    path('plan_estudio/', ReportesPlanDeEstudio.as_view(), name='plan_estudio'),
    path('inscripciones/', ReportesMisInscripciones.as_view(), name='inscripciones'),
    path('porcentaje_avance_carrera/', PromedioYPorcentaje.as_view(), name='porcentaje_avance_carrera'),
    path('datos_censales/', MisDatosPersonales.as_view(), name='datos_censales'),
    path('datos_censales/domicilio/', Domicilio.as_view(), name='domicilio'),
    path('datos_censales/datos_contacto', DatosContacto.as_view(), name='datos_contacto'),
    path('datos_censales/editar_datos_contacto/datos_contacto/', ConfiguracionDatosCelular.as_view(),
         name='editar_datos_contacto'),
    path('datos_censales/discapacidad', Discapacidad.as_view(), name='discapacidad'),
    path('configuracion/', Configuracion.as_view(), name='configuracion'),
]

SIU_Guarani/SIU_app/admin/SIU/models/admin_alumno.py
from django.contrib import admin
from ....models import ALUMNO
from ... import mostrar_carrera_universitaria, mostrar_historial_academico


class AlumnoAdmin(admin.ModelAdmin):
    list_display = ('nombre', 'apellido', 'dni', 'nombre_carrera')
    list_filter = ('dni', 'id_carrera')
    search_fields = ('nombre', 'apellido', 'dni')
    actions = [mostrar_carrera_universitaria, mostrar_historial_academico]

    def nombre_carrera(self, obj):
        return obj.id_carrera
    nombre_carrera.short_description = "Carrera del alumno"


admin.site.register(ALUMNO, AlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_carrera.py
from django.contrib import admin
from ....models import CARRERA


class CarreraAdmin(admin.ModelAdmin):
    list_display = ('nombre_carrera',)


admin.site.register(CARRERA, CarreraAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_cursada_alumno.py
from django.contrib import admin
from ....models import CURSADA_ALUMNO
from ..actions import mostrar_materia_con_parcial


class CursadaAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'id_alumno', 'cursada_del_alumno')
    list_filter = ('id_alumno', 'inscripto', 'aprobo')
    search_fields = ('fecha',)
    actions = [mostrar_materia_con_parcial]

    def cursada_del_alumno(self, obj):
        return obj.id_materia_con_parcial
    cursada_del_alumno.short_description = 'Materias inscriptas del alumno'


admin.site.register(CURSADA_ALUMNO, CursadaAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen.py
from django.contrib import admin
from ....models import EXAMEN, EXAMEN_ALUMNO
from ..filters import RecentDateFilter


class ExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_examen', 'nota_examen', 'nombre_materia')
    list_filter = (RecentDateFilter,)

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_examen_alumno(tabla_examen_alumno):
        nota_examen = tabla_examen_alumno.id_materia_con_examen.id_examen.nota_examen

        if nota_examen >= 4:
            tabla_examen_alumno.aprobo = True
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()
        else:
            tabla_examen_alumno.aprobo = False
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_examen_alumno = EXAMEN_ALUMNO.objects.get(id_materia_con_examen__id_examen__id_examen=obj.id_examen)
        self.actualizo_examen_alumno(tabla_examen_alumno)


admin.site.register(EXAMEN, ExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen_alumno.py
from django.contrib import admin

from ..filters import RecentDateFilter
from ....models import EXAMEN_ALUMNO
from ..actions import mostrar_materia_con_examen


class ExamenAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'nombre_alumno', 'examen_del_alumno')
    list_filter = ('id_alumno', RecentDateFilter)
    actions = [mostrar_materia_con_examen]

    def examen_del_alumno(self, obj):
        return obj.id_materia_con_examen
    examen_del_alumno.short_description = 'Mesa de examen inscripta del alumno'

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'


admin.site.register(EXAMEN_ALUMNO, ExamenAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_historial_academico.py
from django.contrib import admin

from ....models import HISTORIAL_ACADEMICO
from ..filters import RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter
from ..actions import mostrar_cursada_alumno, mostrar_examen_alumno


class HistorialAcademicoAdmin(admin.ModelAdmin):
    list_display = ('nombre_alumno', 'fecha', 'nombre_cursada_alumno', 'nombre_examen_alumno')
    list_filter = (RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter)
    search_fields = ('id_alumno__dni',)
    actions = [mostrar_cursada_alumno, mostrar_examen_alumno]

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'

    def nombre_cursada_alumno(self, obj):
        return obj.id_cursada_alumno
    nombre_cursada_alumno.short_description = 'Cursada regular del alumno'

    def nombre_examen_alumno(self, obj):
        return obj.id_examen_alumno
    nombre_examen_alumno.short_description = 'Mesa de examen del alumno'


admin.site.register(HISTORIAL_ACADEMICO, HistorialAcademicoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_examen.py
from django.contrib import admin
from ....models import MATERIA_CON_EXAMEN
from ..actions import cargo_notas_examen


class MateriaConExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_examen')
    actions = [cargo_notas_examen]

    def nombre_examen(self, obj):
        return obj.id_examen
    nombre_examen.short_description = 'Examen'

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'


admin.site.register(MATERIA_CON_EXAMEN, MateriaConExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_parcial.py
from django.contrib import admin
from ....models import MATERIA_CON_PARCIAL
from ..actions import mostrar_parciales


class MateriaConParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_primer_parcial', 'nombre_segundo_parcial')
    list_filter = ('id_materia', 'id_materia_con_parcial')
    actions = [mostrar_parciales]

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    def nombre_primer_parcial(self, obj):
        return obj.id_primer_parcial
    nombre_primer_parcial.short_description = "Pimer parcial"

    def nombre_segundo_parcial(self, obj):
        return obj.id_segundo_parcial
    nombre_segundo_parcial.short_description = "Segundo parcial"


admin.site.register(MATERIA_CON_PARCIAL, MateriaConParcialAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_parcial.py
from django.contrib import admin
from django.db.models import Q
from ....models import PARCIAL, CURSADA_ALUMNO


class ParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_parcial', 'nota_parcial', 'nota_recuperatorio', 'nota_promocion', 'nombre_materia')
    list_filter = ('nombre_parcial',)

    def nombre_materia(self, obj):
        return obj.id_materia

    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_cursada_alumno(tabla_cursada_alumno):
        nota_primer_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_promocion
        nota_primer_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_parcial
        nota_primer_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_recuperatorio
        nota_segundo_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_promocion
        nota_segundo_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_parcial
        nota_segundo_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_recuperatorio

        if nota_primer_parcial < 4:
            if nota_primer_recuperatorio != 0 and nota_primer_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial != 0 and nota_segundo_parcial < 4)):
            if nota_segundo_recuperatorio != 0 and nota_segundo_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

            elif nota_segundo_recuperatorio >= 4:
                tabla_cursada_alumno.aprobo = True
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if (nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4 and
                nota_segundo_parcial == 0):
            pass
        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial >= 4 or nota_segundo_recuperatorio >= 4 or nota_segundo_promocion >= 4)):
            tabla_cursada_alumno.aprobo = True
            tabla_cursada_alumno.inscripto = False
            tabla_cursada_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_cursada_alumno = CURSADA_ALUMNO.objects.get(
            Q(id_materia_con_parcial__id_primer_parcial__id_parcial=obj.id_parcial) |
            Q(id_materia_con_parcial__id_segundo_parcial__id_parcial=obj.id_parcial)
        )
        self.actualizo_cursada_alumno(tabla_cursada_alumno)


admin.site.register(PARCIAL, ParcialAdmin)

SIU_Guarani/SIU_app/views.py
from django.shortcuts import render

# Create your views here.

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/datos_de_contacto.html
{% extends 'SIU/templates_base/datos_personales_base.html' %}

{% block title %}SIU Guaraní - Datos censales{% endblock %}

{% block style %}
    .tabla_datos_contacto{
        width: 870px;
        height: 285px;
        display: flow;
    }
    .edicion_tabla_datos_contacto {
        width: 870px;
        height: 116px;
        box-sizing: border-box;
        display: table;
        margin-bottom: 20px;

    }
    thead{
        border-color: rgb(128, 128, 128);
        border-collapse: collapse;
        display: table-header-group;
    }
    tr{
        border-color: rgb(128, 128, 128);
        display: table-row;
    }
    th{
        border-collapse: collapse;
        padding: 8px;
        text-align: left;
        vertical-align: bottom;
    }
    tbody{
        border-color: rgb(128, 128, 128);
        display: table-row-group;
    }
    td{
        border-collapse: collapse;
        border-top: 1px solid rgb(221, 221, 221);
        display: table-cell;
        padding: 8px;
        vertical-align: top;
    }
{% endblock %}

{% block titulo_pagina %}Datos de contacto{% endblock %}

{% block navegador_datos_personales %}
        <li><a href="{% url 'SIU:datos_censales' %}" class="li_links">Datos personales</a></li>
        <li><a href="{% url 'SIU:domicilio' %}" class="li_links">Domicilio</a></li>
        <li id="pagina_actual_links"><a href="{% url 'SIU:datos_contacto' %}" class="pagina_actual_texto">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li><a href="{% url 'SIU:discapacidad' %}" class="li_links">Discapacidad</a></li>
{% endblock %}

{% block content %}
    <div class="tabla_datos_contacto">
        <table class="edicion_tabla_datos_contacto">
            <thead>
                <tr>
                    <th style="text-align: left">Tipo</th>
                    <th style="text-align: left">Contacto</th>
                    <th class="elemento_vacio"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td >E-mail principal</td>
                    <td>{{ usuario.id_datos_contacto.correo}}</td>
                    <td><a href="{% url 'SIU:configuracion' %}" style="color: #58B1D1">Cambiar</a> </td>
                </tr>
                <tr>
                    <td>Teléfono Celular</td>
                    <td>{{ usuario.id_datos_contacto.numero_celular}}</td>
                    <td><a href="{% url 'SIU:editar_datos_contacto' %}" style="color: #58B1D1">Cambiar</a> </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/datos_personales.html
{% extends 'SIU/templates_base/datos_personales_base.html' %}
{% load static %}

{% block title %} SIU Guaraní - Datos censales{% endblock %}
{% block style %}
    .imagen_usuario{
        width: 870px;
        height: 125px;
    }

    .edicion_datos_usuario{
        width: 870px;
        height: 550px;
        border: 1px solid #E3E3E3;
        border-radius: 5px;
        background: #F5F5F5;
        margin-bottom: 20px;
        padding-left: 10px;
        padding-right: 10px;
    }
    .sub_edicion_datos_usuario{
        width: 848px;
        height: 960px;
        line-height: 20px
    }

    .datos_usuario {
        width: 848px;
        height: 65px;
        display: flex;
        justify-content: space-between;
        margin-bottom: 5px;
    }

    .sub_datos_usuario{
        width: 413px;
        height: 65px;
        box-sizing: border-box;
    }

    .tabla_familia{
        width: 848px;
        height: 257px;
        border-radius: 5px;
        border: 1px solid rgb(227, 227, 227);
        margin-bottom: 20px;
        padding-left: 10px;
        padding-right: 10px;
    }

    .situacion_familiar{
        width: 826px;
        height: 205px;
    }
    .turno_preferido{
        width: 848px;
        height: 117px;
        border-radius: 5px;
        border: 1px solid #E3E3E3;
    }

    .sub_turno_preferido{
        width: 826px;
        height: 65px;
    }

    .no-select {
        user-select: none; /* Para navegadores modernos */
        -webkit-user-select: none; /* Para navegadores webkit */
        -moz-user-select: none; /* Para navegadores Firefox */
        -ms-user-select: none; /* Para navegadores antiguos de IE */
        background: #EEEEEE;
    }
{% endblock %}
    {% block titulo_pagina %}Datos personales{% endblock %}

    {% block navegador_datos_personales%}
        <li id="pagina_actual_links"><a href="{% url 'SIU:datos_censales' %}" class="pagina_actual_texto">Datos personales</a></li>
        <li><a href="{% url 'SIU:domicilio' %}"  class="li_links">Domicilio</a></li>
        <li><a href="{% url 'SIU:datos_contacto' %}" class="li_links">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li><a href="{% url 'SIU:discapacidad' %}" class="li_links">Discapacidad</a></li>
    {% endblock %}

    {% block content %}
        <div class="imagen_usuario">
            <img src="{% static 'SIU/imagenes/logo-usuario.png' %}" alt="foto usuario">
        </div>
        <!-- Contenido de forms -->
        <div class="edicion_datos_usuario">
            <div class="sub_edicion_datos_usuario">
                <!--Datos del usuario-->
                <div class="datos_usuario">
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.apellido.id_for_label }}">{{ form_usuario.apellido.label }}</label><br>
                        {{ form_usuario.apellido }}
                    </div>
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.nombre.id_for_label }}">{{ form_usuario.nombre.label }}</label><br>
                        {{ form_usuario.nombre }}
                    </div>
                </div>
                <div class="datos_usuario">
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.tipo_de_documento.id_for_label }}">{{ form_usuario.tipo_de_documento.label }}</label><br>
                        {{ form_usuario.tipo_de_documento }}
                    </div>
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.numero_de_documento.id_for_label }}">{{ form_usuario.numero_de_documento.label }}</label><br>
                        {{ form_usuario.numero_de_documento }}
                    </div>
                </div>
                <div class="datos_usuario">
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.numero_de_cuil.id_for_label }}">{{ form_usuario.numero_de_cuil.label }}</label><br>
                        {{ form_usuario.numero_de_cuil }}
                    </div>
                    <div class="sub_datos_usuario">
                        <label for="{{ form_usuario.genero.id_for_label }}">{{ form_usuario.genero.label }}</label><br>
                        {{ form_usuario.genero }}
                    </div>
                </div><br>

                <!--Datos familiares del usuario-->
                <div class="tabla_familia">
                    <h3 class="texto_gris">Situación familiar</h3>
                    <div class="situacion_familiar">
                        <div class="datos_usuario">
                            <div class="sub_datos_usuario">
                                <label for="{{  form_familia.name }}"><strong>{{  form_familia.estado_civil.label }}</strong> </label><br>
                                {{ form_familia.estado_civil }}
                            </div>
                        </div>
                        <div class="datos_usuario">
                            <div class="sub_datos_usuario">
                                <label for="{{ form_familia.name }}">{{ form_familia.cantidad_hijos.label }}</label><br>
                                {{ form_familia.cantidad_hijos }}
                            </div>
                            <div class="sub_datos_usuario">
                                <label for="{{ form_familia.name }}">{{ form_familia.cantidad_familiares.label }}</label><br>
                                {{ form_familia.cantidad_familiares }}
                            </div>
                        </div>
                        <div class="datos_usuario">
                            <div class="sub_datos_usuario">
                                <label for="{{ form_familia.name }}"><strong>{{ form_familia.situacion_padre.label }}</strong> </label><br>
                                {{ form_familia.situacion_padre }}
                            </div>
                            <div class="sub_datos_usuario">
                                <label for="{{ form_familia.name }}"><strong>{{ form_familia.situacion_madre.label }}</strong> </label><br>
                                {{ form_familia.situacion_madre }}
                            </div>
                        </div>
                    </div>
                </div>
                <button id="button_aceptar" class="boton" style="float: right;"  type="submit">Guardar</button>
            </div>

        </div>
    {% endblock %}

{% block script %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // IDs de los inputs a modificar
            let inputIds = ['apellido', 'nombre', 'tipo_documento', 'numero_documento', 'numero_cuil', 'genero'];

            inputIds.forEach(function(id) {
                let input = document.getElementById(id);

                if (input) {
                    // Agregar la clase no-select
                    input.classList.add('no-select');

                    // Hacer que el input sea readonly
                    input.readOnly = true;

                    // Prevenir que el input reciba el foco
                    input.addEventListener('focus', function(event) {
                        event.preventDefault();
                    });
                }
            });
        });
    </script>
{% endblock %}

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/discapacidad.html
{% extends 'SIU/templates_base/datos_personales_base.html' %}

{% block title %}SIU Guaraní - Datos censales{% endblock %}

{% block style %}
    .tabla_discapacidad{
        width: 870px;
        height: 102px;
        border-radius: 5px;
        background: #F5F5F5;
        border: 1px solid #E3E3E3;
    }
    .condicion_discapacidad{
        width: 848px;
        height: 45px;
    }
{% endblock %}

{% block titulo_pagina %}Discapacidad{% endblock %}

{% block navegador_datos_personales %}
        <li><a href="{% url 'SIU:datos_censales' %}" class="li_links">Datos personales</a></li>
        <li><a href="{% url 'SIU:domicilio' %}" class="li_links">Domicilio</a></li>
        <li><a href="{% url 'SIU:datos_contacto' %}" class="li_links">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li id="pagina_actual_links"><a href="{% url 'SIU:discapacidad' %}" class="pagina_actual_texto">Discapacidad</a></li>
{% endblock %}

{% block content %}
        <div class="tabla_discapacidad ">
            <h3 class="texto_gris">Condición de Discapacidad</h3>
            <div class="condicion_discapacidad ">
                <form method="post">
                    <input type="checkbox" id="mi_checkbox" name="checkbox_no_tiene">
                    <label for="mi_checkbox">No presento ninguna condición que implique Discapacidad</label><br>
                    <input type="checkbox" id="mi_checkbox_discapacidad" name="checkbox_si_tiene">
                    <label for="mi_checkbox_discapacidad">Declaro condición de discapacidad</label>
                </form>
            </div>
        </div>
{% endblock %}

SIU_Guarani/SIU_app/templates/SIU/datos_alumno/domicilio.html
{% extends 'SIU/templates_base/datos_personales_base.html' %}

{% block title %}SIU Guaraní - Datos censales{% endblock %}

{% block style %}
    .domicilio_durante_clases{
        width: 840px;
        height: 440px;
        background: #F5F5F5;
        border-radius: 5px;
        display: flow;
        align-items: center;
        align-content: center;
        border: 1px solid rgb(227, 227, 227);
        box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 1px 0px inset;
        padding-left: 10px;
        padding-right: 10px;
        margin-bottom: 20px;
        line-height: 20px;
    }
    .edicion_domicilio_durante_clases{
        width: 848px;
        height: 375px;
        line-height: 20px;
    }

    .cartel {
        background-color: #f8d7da; /* Color de fondo del cartel */
        color: #721c24; /* Color del texto del cartel */
        border: 1px solid #f5c6cb; /* Borde del cartel */
        padding: 10px; /* Espaciado interno del cartel */
        margin-bottom: 20px; /* Margen inferior del cartel para separarlo de otros elementos */
        border-radius: 5px; /* Bordes redondeados del cartel */
        text-align: center;
    }

    .contenido_simple{
        width: 848px;
        height: 65px;
        line-height: 20px;
        margin-bottom: 5px;
        cursor: pointer;
    }
    .contenido_compuesto{
        width: 848px;
        height: 65px;
        display: flex;
        justify-content: space-between;
        margin-bottom: 5px;
        line-height: 20px;
        cursor: pointer;
    }
{% endblock %}

{% block titulo_pagina %}Domicilio{% endblock %}

{% block navegador_datos_personales %}
        <li><a href="{% url 'SIU:datos_censales' %}" class="li_links">Datos personales</a></li>
        <li id="pagina_actual_links"><a href="{% url 'SIU:domicilio' %}" class="pagina_actual_texto">Domicilio</a></li>
        <li><a href="{% url 'SIU:datos_contacto' %}" class="li_links">Datos de contacto</a></li>
        <li><a href="{{ url_estudios }}" class="li_links">Estudios</a></li>
        <li><a href="{{ url_allegados }}" class="li_links">Allegados</a></li>
        <li><a href="{% url 'SIU:discapacidad' %}" class="li_links">Discapacidad</a></li>
{% endblock %}

{% block content %}
    <div class="domicilio_durante_clases">
        <h3 class="texto_gris">Domicilio durante el período de clases</h3>
        <div class="edicion_domicilio_durante_clases">
            <div class="contenido_simple">
                <label for="{{ form.name }}"><strong>{{ form.calle.label }}</strong></label><br>
                {{ form.calle }}
            </div>
            <div class="contenido_compuesto">
                <div style="width: 157px; height: 65px">
                    <label for="{{ form.name }}"><strong>{{ form.numero_calle.label }}</strong></label><br>
                    {{ form.numero_calle }}
                </div>
                <div style="width: 157px; height: 65px">
                    <label for="{{ form.name }}">{{ form.piso.label }}</label><br>
                    {{ form.piso }}
                </div>
                <div style="width: 157px; height: 65px">
                    <label for="{{ form.name }}">{{ form.departamento.label }}</label><br>
                    {{ form.departamento }}
                </div>
                <div style="width: 157px; height: 65px">
                    <label for="{{ form.name }}">{{ form.unidad.label }}</label><br>
                    {{ form.unidad }}
                </div>
            </div>
            <div class="contenido_simple">
                <label for="{{ form.name }}"><strong>{{ form.localidad.label }}</strong></label><br>
                {{ form.localidad }}
            </div>
            <div class="contenido_compuesto">
                <div style="width: 332px; height: 65px" >
                    <label for="{{ form.name }}"><strong>{{ form.codigo_postal.label }}</strong></label><br>
                    {{ form.codigo_postal }}
                </div>
                <div style="width: 332px; height: 65px" >
                    <label for="{{ form.name }}">{{ form.barrio.label }}</label><br>
                    {{ form.barrio }}
                </div>
            </div>
            <div class="contenido_compuesto">
                <div style="width: 332px; height: 65px">
                    <label for="{{ form.name }}">{{ form.tipo_vivienda.label }}</label><br>
                    {{ form.tipo_vivienda }}
                </div>
                <div style="width: 332px; height: 65px">
                    <label for="{{ form.name }}">{{ form.tipo_convivencia.label }}</label><br>
                    {{ form.tipo_convivencia }}
                </div>
            </div><button type="submit" class="boton" style="float: right;" name="guardar_cambios">Guardar</button>
        </div>
    </div>
{% endblock %}