SIU_Guarani/SIU_Guarani/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SIU_app.urls')),  # Vinculo todas las urls de mi app SIU
]

SIU_Guarani/SIU_app/urls.py
from django.urls import path
from .views import *

app_name = 'SIU' #Se especifica un nombre, para distinguir las urls similares de diferentes apps.
urlpatterns = [
    path('logout/', CerrarSesion.as_view(), name='cerrar_sesion'),
    path('acceso/', Logeo.as_view(), name='acceso'),
    path('acceso/recuperar', OlvidoContrasenna.as_view(), name='recuperar'),
    path('acceso/alta_usuario_cursos', CreoUsuario.as_view(), name='alta_usuario'),
    path('inicio_alumno/', InicioAlumno.as_view(), name='inicio_alumno'),
    path('materia/', InscripcionMaterias.as_view(), name='materia'),
    path('examen/', InscripcionExamenes.as_view(), name='examen'),
    path('plan_estudio/', ReportesPlanDeEstudio.as_view(), name='plan_estudio'),
    path('inscripciones/', ReportesMisInscripciones.as_view(), name='inscripciones'),
    path('porcentaje_avance_carrera/', PromedioYPorcentaje.as_view(), name='porcentaje_avance_carrera'),
    path('datos_censales/', MisDatosPersonales.as_view(), name='datos_censales'),
    path('datos_censales/domicilio/', Domicilio.as_view(), name='domicilio'),
    path('datos_censales/datos_contacto', DatosContacto.as_view(), name='datos_contacto'),
    path('datos_censales/editar_datos_contacto/datos_contacto/', ConfiguracionDatosCelular.as_view(),
         name='editar_datos_contacto'),
    path('datos_censales/discapacidad', Discapacidad.as_view(), name='discapacidad'),
    path('configuracion/', Configuracion.as_view(), name='configuracion'),
]

SIU_Guarani/SIU_app/admin/SIU/models/admin_alumno.py
from django.contrib import admin
from ....models import ALUMNO
from ... import mostrar_carrera_universitaria, mostrar_historial_academico


class AlumnoAdmin(admin.ModelAdmin):
    list_display = ('nombre', 'apellido', 'dni', 'nombre_carrera')
    list_filter = ('dni', 'id_carrera')
    search_fields = ('nombre', 'apellido', 'dni')
    actions = [mostrar_carrera_universitaria, mostrar_historial_academico]

    def nombre_carrera(self, obj):
        return obj.id_carrera
    nombre_carrera.short_description = "Carrera del alumno"


admin.site.register(ALUMNO, AlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_carrera.py
from django.contrib import admin
from ....models import CARRERA


class CarreraAdmin(admin.ModelAdmin):
    list_display = ('nombre_carrera',)


admin.site.register(CARRERA, CarreraAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_cursada_alumno.py
from django.contrib import admin
from ....models import CURSADA_ALUMNO
from ..actions import mostrar_materia_con_parcial


class CursadaAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'id_alumno', 'cursada_del_alumno')
    list_filter = ('id_alumno', 'inscripto', 'aprobo')
    search_fields = ('fecha',)
    actions = [mostrar_materia_con_parcial]

    def cursada_del_alumno(self, obj):
        return obj.id_materia_con_parcial
    cursada_del_alumno.short_description = 'Materias inscriptas del alumno'


admin.site.register(CURSADA_ALUMNO, CursadaAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen.py
from django.contrib import admin
from ....models import EXAMEN, EXAMEN_ALUMNO
from ..filters import RecentDateFilter


class ExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_examen', 'nota_examen', 'nombre_materia')
    list_filter = (RecentDateFilter,)

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_examen_alumno(tabla_examen_alumno):
        nota_examen = tabla_examen_alumno.id_materia_con_examen.id_examen.nota_examen

        if nota_examen >= 4:
            tabla_examen_alumno.aprobo = True
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()
        else:
            tabla_examen_alumno.aprobo = False
            tabla_examen_alumno.inscripto = False
            tabla_examen_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_examen_alumno = EXAMEN_ALUMNO.objects.get(id_materia_con_examen__id_examen__id_examen=obj.id_examen)
        self.actualizo_examen_alumno(tabla_examen_alumno)


admin.site.register(EXAMEN, ExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_examen_alumno.py
from django.contrib import admin

from ..filters import RecentDateFilter
from ....models import EXAMEN_ALUMNO
from ..actions import mostrar_materia_con_examen


class ExamenAlumnoAdmin(admin.ModelAdmin):
    list_display = ('fecha', 'aprobo', 'inscripto', 'nombre_alumno', 'examen_del_alumno')
    list_filter = ('id_alumno', RecentDateFilter)
    actions = [mostrar_materia_con_examen]

    def examen_del_alumno(self, obj):
        return obj.id_materia_con_examen
    examen_del_alumno.short_description = 'Mesa de examen inscripta del alumno'

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'


admin.site.register(EXAMEN_ALUMNO, ExamenAlumnoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_historial_academico.py
from django.contrib import admin

from ....models import HISTORIAL_ACADEMICO
from ..filters import RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter
from ..actions import mostrar_cursada_alumno, mostrar_examen_alumno


class HistorialAcademicoAdmin(admin.ModelAdmin):
    list_display = ('nombre_alumno', 'fecha', 'nombre_cursada_alumno', 'nombre_examen_alumno')
    list_filter = (RecentDateFilter, InscriptoMateriasFilter, InscriptoExamenesFilter)
    search_fields = ('id_alumno__dni',)
    actions = [mostrar_cursada_alumno, mostrar_examen_alumno]

    def nombre_alumno(self, obj):
        return obj.id_alumno
    nombre_alumno.short_description = 'Alumnos'

    def nombre_cursada_alumno(self, obj):
        return obj.id_cursada_alumno
    nombre_cursada_alumno.short_description = 'Cursada regular del alumno'

    def nombre_examen_alumno(self, obj):
        return obj.id_examen_alumno
    nombre_examen_alumno.short_description = 'Mesa de examen del alumno'


admin.site.register(HISTORIAL_ACADEMICO, HistorialAcademicoAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_examen.py
from django.contrib import admin
from ....models import MATERIA_CON_EXAMEN
from ..actions import cargo_notas_examen


class MateriaConExamenAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_examen')
    actions = [cargo_notas_examen]

    def nombre_examen(self, obj):
        return obj.id_examen
    nombre_examen.short_description = 'Examen'

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'


admin.site.register(MATERIA_CON_EXAMEN, MateriaConExamenAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_materia_con_parcial.py
from django.contrib import admin
from ....models import MATERIA_CON_PARCIAL
from ..actions import mostrar_parciales


class MateriaConParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_materia', 'nombre_primer_parcial', 'nombre_segundo_parcial')
    list_filter = ('id_materia', 'id_materia_con_parcial')
    actions = [mostrar_parciales]

    def nombre_materia(self, obj):
        return obj.id_materia
    nombre_materia.short_description = 'Materia'

    def nombre_primer_parcial(self, obj):
        return obj.id_primer_parcial
    nombre_primer_parcial.short_description = "Pimer parcial"

    def nombre_segundo_parcial(self, obj):
        return obj.id_segundo_parcial
    nombre_segundo_parcial.short_description = "Segundo parcial"


admin.site.register(MATERIA_CON_PARCIAL, MateriaConParcialAdmin)

SIU_Guarani/SIU_app/admin/SIU/models/admin_parcial.py
from django.contrib import admin
from django.db.models import Q
from ....models import PARCIAL, CURSADA_ALUMNO


class ParcialAdmin(admin.ModelAdmin):
    list_display = ('nombre_parcial', 'nota_parcial', 'nota_recuperatorio', 'nota_promocion', 'nombre_materia')
    list_filter = ('nombre_parcial',)

    def nombre_materia(self, obj):
        return obj.id_materia

    nombre_materia.short_description = 'Materia'

    @staticmethod
    def actualizo_cursada_alumno(tabla_cursada_alumno):
        nota_primer_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_promocion
        nota_primer_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_parcial
        nota_primer_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_primer_parcial.nota_recuperatorio
        nota_segundo_promocion = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_promocion
        nota_segundo_parcial = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_parcial
        nota_segundo_recuperatorio = tabla_cursada_alumno.id_materia_con_parcial.id_segundo_parcial.nota_recuperatorio

        if nota_primer_parcial < 4:
            if nota_primer_recuperatorio != 0 and nota_primer_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial != 0 and nota_segundo_parcial < 4)):
            if nota_segundo_recuperatorio != 0 and nota_segundo_recuperatorio < 4:
                tabla_cursada_alumno.aprobo = False
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

            elif nota_segundo_recuperatorio >= 4:
                tabla_cursada_alumno.aprobo = True
                tabla_cursada_alumno.inscripto = False
                tabla_cursada_alumno.save()

        if (nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4 and
                nota_segundo_parcial == 0):
            pass
        if ((nota_primer_parcial >= 4 or nota_primer_recuperatorio >= 4 or nota_primer_promocion >= 4) and
                (nota_segundo_parcial >= 4 or nota_segundo_recuperatorio >= 4 or nota_segundo_promocion >= 4)):
            tabla_cursada_alumno.aprobo = True
            tabla_cursada_alumno.inscripto = False
            tabla_cursada_alumno.save()

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        tabla_cursada_alumno = CURSADA_ALUMNO.objects.get(
            Q(id_materia_con_parcial__id_primer_parcial__id_parcial=obj.id_parcial) |
            Q(id_materia_con_parcial__id_segundo_parcial__id_parcial=obj.id_parcial)
        )
        self.actualizo_cursada_alumno(tabla_cursada_alumno)


admin.site.register(PARCIAL, ParcialAdmin)

SIU_Guarani/SIU_app/views.py
from django.shortcuts import render

# Create your views here.

SIU_Guarani/SIU_app/templates/SIU/acceso/acceso.html
{% extends 'SIU/templates_base/acceso_base.html' %}

{% block title %} SIU-Guaraní - Acceso {% endblock %}

{% block content %}
    <style>
        #2_columnas {
            width: 1170px;
            height: 428px;
            display: flex;
        }
        #columna_1 {
            width: 470px;
            height: 428px;
            margin-left: 350px;
            float: left;
        }
        #columna_2 {
            width: 670px;
            height: 192px;
            margin-right: 350px;
            float: right;
        }
        h1 {
            color: #8D8D8D;
        }
        li{
            font-size: 15px;
            margin-bottom: 5px;
        }
        hr{
            border: 1px solid  rgb(238, 238, 238);
            display: block;
            margin-bottom: 20px;
            margin-top: 20px;
            margin-block-end: 20px;
            margin-block-start: 20px;
        }
    </style>

    <div id="2_columnas">
        <div id="columna_1">
            <hr>
            <h1>Ingresá tus datos</h1>
            <form method="post" action="">{% csrf_token %}
                <label for="{{ form.name }}">Usuario</label><br>
                    {{ form.username }}<br><br>
                <label for="{{ form.name }}">Contraseña</label><br>
                    {{ form.password }}<br><br>
                <!--Con esto me va a la pagina donde quiere ingresar sin estar logeado-->
                <input type="hidden" name="next" value="{{ request.GET.next }}">

                <button class="boton" type="submit">Ingresar</button><br><br>
                {% if usuario_incorrecto %}
                    <div class="fallos_formulario" style="width: 470px; height: 58px">
                        <p>El nombre de usuario y/o contraseña es incorrecto. Por favor intenta de nuevo.</p>
                    </div><br>
                {% endif %}

                <a href="{% url 'SIU:recuperar' %}" style="text-decoration: none; color: #58B1D1">¿Olvidaste tu contraseña o sos un usuario nuevo?</a><br><br><hr>
                <p>Si deseás inscribirte a cursos, <strong>y no tenés usuario y clave de acceso al sistema</strong>, podés crearlo accediendo <a href="{% url 'SIU:alta_usuario' %}" style="text-decoration: none; color: #58B1D1">aquí.</a></p><hr>
            </form>
        </div>

        <div id="columna_2">
            <h1>SIU Guaraní</h1>
            <p>Algunas de las cosas que podés hacer con este sistema son:</p>
            <ul>
                <li>Inscribirte a materias y exámenes.</li>
                <li>Consultar el plan de tu propuesta.</li>
                <li>Consultar tu historia académica.</li>
                <li>Actualizar tus datos personales.</li>
                <li>Recibir alertas sobre periodos de inscripción o vencimiento de exámenes finales.</li>
            </ul>
        </div>
    </div>

{% endblock %}

{% load static %}

SIU_Guarani/SIU_app/templates/SIU/acceso/olvido_contrasenna.html
{% extends 'SIU/templates_base/acceso_base.html' %}

{% block title %} SIU-Guaraní - Acceso {% endblock %}

{% block content %}
    <style>
        #2_columnas{
            width: 1170px;
            height: 428px;
        }
        #columna_1{
            width: 470px;
            height: 428px;
            float: left;
            margin-left: 350px;
        }
        #columna_2{
            width: 670px;
            height: 192px;
            float: right;
            margin-right: 350px;
        }
        h1{
            color: #8D8D8D;
            font-size: 24px;
            line-height: 32px;
        }
        li{
            font-size: 15px;
            margin-bottom: 5px;
        }
    </style>

    <div id="2_columnas">
        <div id="columna_1">
            <h1> Recuperar contraseña </h1>
            <p> Ingresa tu número de documento y se te enviará un mail con instrucciones para reestablecer tu contraseña</p>
            <form method="post">{% csrf_token %}
                <label for="{{ form.name }}">{{ form.tipo_de_documento.label }}</label><br>
                    {{ form.tipo_de_documento }}<br><br>
                <label for="{{ form.name }}">{{ form.numero_documento.label }}</label><br>
                    {{ form.numero_documento }}<br><br>
                <button class="boton" type="submit" style="width: 90px">Continuar</button><br><br>
            </form>
            <div id="notificacion" class="fallos_formulario" style="width: 470px;height: 58px; display: none">
                <p id="alerta_error"></p>
            </div>
        </div>
        <div id="columna_2">
            <h1>SIU Guaraní</h1>
            <p>Algunas de las cosas que podés hacer con este sistema son: </p>
            <ul>
                <li>Inscribirte a materias y exámenes.</li>
                <li>Consultar el plan de tu propuesta.</li>
                <li>Consultar tu historia académica.</li>
                <li>Actualizar tus datos personales.</li>
                <li>Recibir alertas sobre periodos de inscripción o vencimiento de exámenes finales.</li>
            </ul>
        </div>
    </div>

<script>
    const campoVacio = {{ vacio|lower }};

    if (campoVacio){
        let mensaje = document.getElementById('alerta_error');
        let muestroNotificacion = document.getElementById('notificacion');
        muestroNotificacion.style.display = 'block';
        muestroNotificacion.style.display = 'flex';
        mensaje.innerText = 'El campo documento es requerido';
    }
</script>
<script>
    const usuarioEncontrado = {{ usuario_encontrado|lower }};

    if (usuarioEncontrado){
        let mensaje = document.getElementById('alerta_error');
        let muestroNotificacion = document.getElementById('notificacion');
        muestroNotificacion.style.display = 'block';
        muestroNotificacion.style.display = 'flex';
        mensaje.innerText = 'Se envio el correo al usuario'
    }
    if (!usuarioEncontrado && !campoVacio){
        let mensaje = document.getElementById('alerta_error');
        let muestroNotificacion = document.getElementById('notificacion');
        muestroNotificacion.style.display = 'block';
        muestroNotificacion.style.display = 'flex';
        mensaje.innerText = 'No existe la persona segun el nro de documento';
    }
</script>
{% endblock %}